In [10]:
import numpy as np
from PIL import Image 
import matplotlib.pyplot as plt


In [136]:
im = Image.open('../chlng/Downloads/dbmf/image.jpeg')
im = im.convert('RGBA')

data = np.array(im)
red, green, blue, alpha = data.T

background = (red == 255) & (blue == 184) & (green == 247) 
shade = (red >= 240) & (blue >= 160) & (green >= 230) 

data[...,:-1][background.T] = (255,255,255)
data[...,:-1][shade.T] = (255,255,255)
im2 = Image.fromarray(data)
im2.show()
im2.save("../chlng/Downloads/dbmf/poster-white-bg.png","PNG")
##rgb = data[:,:,:3]
##color = [242,246,219]
##black = [0,0,0,255]
##white = [255,255,255,255]
##mask = np.all(rgb == color, axis = -1)
##data[mask] = white


In [137]:
im = Image.open('../chlng/Downloads/dbmf/poster-white-bg.png')
im = im.convert('RGBA')
datas = im.getdata()

newData = []
for i in datas:
    if (i[0] == 255 & i[1] == 255 & i[2] == 255):
        newData.append((255,255,255,0))
        
    else:
        newData.append(i)
        
im2.putdata(newData)
im2.show()
im2.save("../chlng/Downloads/dbmf/poster-del-bg.png","PNG")

In [69]:
data[..., :-1]
data[...][background.T]

array([], shape=(0, 4), dtype=uint8)

In [56]:
from numpy import arange
tmp = arange(16).reshape(2,2,2,2)
print (tmp)


[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [57]:
print (tmp[...,1])

[[[ 1  3]
  [ 5  7]]

 [[ 9 11]
  [13 15]]]


In [63]:
print (tmp[-1])

[[[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]


In [59]:
print (tmp[-1,...][1])

[[12 13]
 [14 15]]


In [64]:
print (tmp[-1,...][1][1][1])

15


In [66]:
data = np.array(im)
red, green, blue, alpha = data

background = (red == 242) & (blue == 219) & (green == 246)&(alpha == 1)

data[..., :-1][background] = (255,255,255)

ValueError: too many values to unpack (expected 4)